### ISSUE TITLE
There is a problem with the output

### ISSUE THREAD

**Issue by defaul0t** [six2dez/ipcdn#4]
There is a problem with the output

only not cdn ？
use ./ipcdn -m not cdn  output all data
![1670383060787](https://user-images.githubusercontent.com/49946499/206079821-d9da3a9d-d254-4754-b863-6197c3e1e2cb.png)

**Comment by six2dez** [comment]
Fixed by https://github.com/six2dez/ipcdn/commit/114dba15eeb7dabbfafb17a708d41fbb61db71a8
